Готовая верстка двух страниц
htmlacademy-htmlcss/2060893-sedona-35 pull request #2
Opened 2022-10-04 15:41 UTC by NickSmrnv

2022-10-04 16:19 UTC, NickSmrnv reviewed
Готовая верстка

2022-10-05 13:52 UTC, vadimrahmanov requested changes

2022-10-05 13:52 UTC, vadimrahmanov commented on .editorconfig
> +indent_style = tab
Файл должен соответствовать код-гайду академии.

https://codeguide.academy/html-css.html 

Нужно поменять обратно.

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
>  </html>
Отступы не соответствуют код-гайду академии, да и в целом как-то не эстетично использовать такие огромные отступы и код очень не удобно читать. Поправь пожалуйста.

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +				</a>
Лого не является частью навигации. Следует вынести повыше.

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +			<h1></h1>
Пустой элемент. Наверное забыл написать заголовок.

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +						<a class="navigation-link navigation-link-current" href="index.html"
Ссылки, которые ведут на самих себя, могут быть без атрибута.

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +						<a class="navigation-link" href="about.html">О нас</a>
Для ссылок, адрес которых неизвестен, можно использовать атрибут href с решёткой href="#".
В проекте не будет страницы about.html.

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +		<main class="main-index">
Выше ты используешь для `header` класс `page-header`, здесь уже `main-index, а не `page-main`. Нужно придерживаться одного стиля наименования. 

https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-01

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +		<meta name="viewport" content="width=device-width, initial-scale=1" />
Для тэга `<meta>` не нужен закрывающий `/`

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +			</section>
Наглядный список преимуществ, но почему-то размечен иначе, хотя ниже список рекомендаций размечен как надо.

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +				<a class="find-hotel-button" href="hotels.html"
Это не ссылка на другую страницу. Если посмотреть внимательно дизайн, то можно найти то, для чего предназначена эта кнопка.

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +							<span class="visually-hidden">Ютьюб</span>
Следует использовать оригинальные названия (YouTube) в таких случаях

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +							<img class="footer-youtube" src="" alt="Иконка сайта Ютьюб." />
Тут тоже самое, что и сверху.

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +						<a class="button" href="https://vk.com/htmlacademy">
Я бы использовал класс `footer-social-link` в таком случае. Мне кажется это будет более гармонично.

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +					<li class="recommend-item"></li>
Пустой элемент `<li>`

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +					</p>
В список нельзя вставлять элементы не обернув их заранее как элемент-списка (li).

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +					</p>
Тоже самое, что и выше.

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +					<img class="page-header-logo" src="" alt="Логотип города Седона" />
Для тэга `<img>` не нужен закрывающий /

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +			<img class="main-logo" src="" alt="Логотип сайта Седона." />
Для тэга `<img>` не нужен закрывающий /

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +				<img src="" alt="Здание с кафе в городе Седона" />
Для тэга `<img>` не нужен закрывающий /

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +				<img src="" alt="Фото каньона" />
Для тэга `<img>` не нужен закрывающий /

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +						<img class="recommend-home" src="" alt="Логотип домика." />
Для тэга `<img>` не нужен закрывающий /

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +					<img class="recommend-souvenirs" src="" alt="Логотип подарка." />
Для тэга `<img>` не нужен закрывающий /

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +				</h1>
На странице должен быть только один заголовок высшего уровня (h1)

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +					<img class="recommend-food" src="" alt="Логотип гамбургера." />
Для тэга `<img>` не нужен закрывающий /

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +					<input type="email" name="E-mail" placeholder="Ваш e-mail" required />
Не нужно использовать для самозакрывающих тэгов /

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +								class="footer-vk"
Более лаконично бы смотрелся класс `footer-social-img`, а то получается, что у тебя всё чётко распределено по секциям -> footer-social, footer-contacts, footer-partner, а тут footer-vk как-будто это отдельная секция.

2022-10-05 13:52 UTC, vadimrahmanov commented on index.html
> +								class="footer-telegram"
Тоже самое, что и выше.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +</html>
Не нужно использовать в конце самозакрывающихся элементов `/`

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +		<main class="main-inner">
Тоже самое, что и на главной странице - Выше ты используешь для header класс page-header, здесь уже main-inner, а не page-main`. Нужно придерживаться одного стиля наименования.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +			<header class="inner-header">
`header` используется только для шапки сайта (которая повторяется на всех страницах). 
Исключение: тэг `<article>`, где своя структура.

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-01

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +						<a class="navigation-link" href="about.html">О нас</a>
Для ссылок, адрес которых неизвестен, можно использовать атрибут href с решёткой href="#".
В проекте не будет страницы about.html.

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +						<a class="navigation-link" href="index.html">Главное</a>
Ссылки, которые ведут на самих себя, могут быть без атрибута.

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +				<a class="navigation-logo" href="index.html">
Лого не является частью навигации. Следует вынести повыше.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +			<section class="catalog-products">
Я считаю, что фильтры не следует называть продуктами (products), т.к по сути это ещё не продукты, а сами продукты уже последуют ниже, когда пользователь настроит фильтры по своему желанию.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +									<input class="control-input" type="checkbox" name="wi-fi" />
Здесь можно использовать такой же принцип, как у тебя ниже. То есть указать общий атрибут name, а затем разный value

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +					<button class="button-filter-reset" type="submit">Сбросить</button>
У формы может быть только один элемент с типом "submit"

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +						<legend class="catalog-filter-title">Стоимость,₽:</legend>
Отсутствуют элементы отвечающие за стоимость.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +				<h2 class="products-found">Найдено гостиниц:</h2>
Здесь бы следовало бы сделать более осмысленный заголовок. Найдено гостиниц - констатация факта. А заголовок может быть например скрытым - `Результаты поиска`

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +						<a class="product-card-link" href="product.html">
Такой страницы не будет в проекте. Можно просто поставить # в атрибуте `href`
Это касается всех ссылок в этом списке.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +						<a class="product-card-button button-favorites button-current"
Для действий на странице должны использоваться  `<button>`

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +						<a class="product-card-button button-favorites">В избранное</a>
Для действий на странице должны использоваться  `<button>`

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +						<a class="product-card-button button-favorites">В избранное</a>
Для действий на странице должны использоваться  `<button>`

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +						<a class="product-card-button button-favorites">В избранное</a>
Для действий на странице должны использоваться  `<button>`

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +						<a class="product-card-button button-favorites">В избранное</a>
Для действий на странице должны использоваться  `<button>`

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +		</footer>
По `footer` те же самые замечания, что и на главной странице.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +					</li>
Отсутсвует рейтинг, а также количество звёзд.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +					</li>
Отсутсвует рейтинг, а также количество звёзд.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +					</li>
Отсутсвует рейтинг, а также количество звёзд.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +					</li>
Отсутсвует рейтинг, а также количество звёзд.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +					</li>
Отсутсвует рейтинг, а также количество звёзд.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +				<h2 class="visually-hidden">Каталог товаров с фильтрами</h2>
Здесь бы следовало бы указать на то, что это каталог отелей, а не физических товаров.

2022-10-05 13:52 UTC, vadimrahmanov commented on hotels.html
> +				</a>
Для действий на странице должны использоваться  `<button>`

https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-03

2022-10-07 16:43 UTC, vadimrahmanov approved these changes

2022-10-07 16:43 UTC, merged