Построение крупных сеток
htmlacademy-htmlcss/2060893-sedona-35 pull request #6
Opened 2022-10-23 14:17 UTC by NickSmrnv

2022-11-03 16:28 UTC, vadimrahmanov requested changes
У тебя пагинация и подписка за пределами `<main>`, поэтому у тебя была проблема с шириной.

![Screenshot 2022-11-03 at 16 27 36](https://user-images.githubusercontent.com/53314530/199778101-cf97fcb8-d969-411a-85bb-d9179515a494.png)

2022-11-03 16:28 UTC, vadimrahmanov commented on index.html
> +            </svg>
Это можно просто через `<img>` добавить

2022-11-03 16:28 UTC, vadimrahmanov commented on hotels.html
> +        -->
Удали закомменченый участок)

2022-11-03 16:28 UTC, vadimrahmanov commented on hotels.html
> +              </svg>
Это можно просто через `<img>` добавить

2022-11-03 16:28 UTC, vadimrahmanov commented on hotels.html
> +              </svg>
Это можно просто через `<img>` добавить

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +  grid-template-columns: 1fr 1fr 1fr;
Здесь также можно использовать `grid-template-columns: repeat(3, 1fr);`, будешь вообще профи хД

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +  width: 1060px;
Это лишнее.

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +}
Я полагаю, что это временно. Не забудь удалить потом.

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +.button-model {
Наверное ты имел в виду modal?

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
>  }
Не забудь указывать правильный курсор для интерактивных элементов (кнопки и т.д).

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +.hero-preview{
пробел перед скобкой

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +}
Это делается гораздо проще и грамотнее. Если нужна с этим помощь, то дай знать.

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +  height: 485px;
Здесь не должно быть высоты.

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +  padding: 92px 112.5px 0;
что за .5 ? :D Лучше использовать с пикселями ровные значения.

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +  padding: 103px 112.5px 0;
Тоже самое, что я ниже написал.

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +  padding: 0;
Не совсем понятно для чего этот селектор.

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +}
Что за .rec? Зачем это?

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +}
Попробуй сделать без этих .rec

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +
Не нужно фиксировать ширину.

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
> +  padding: 8px 57.5px;
Не надо .5 в пикселях использовать.

2022-11-03 16:28 UTC, vadimrahmanov commented on styles/styles.css
>  }
Честно говоря замудренно слишком у тебя это. Можно было просто с флексами сделать. Можешь в принципе и так оставить если пиксельперфект проходит.

2022-11-05 12:22 UTC, NickSmrnv commented on styles/styles.css
> +}
Даю знать!

2022-11-08 15:59 UTC, merged